### ISSUE TITLE
lttng-schedtop output results outside the specified timerange

### ISSUE THREAD

**Issue by jdesfossez** [lttng/lttng-analyses#45] opened 2016-04-22 19:53 UTC
With that trace:
http://secretaire.dorsal.polymtl.ca/~fgiraldeau/traces/cyclictest-20160224.tar.gz

$ lttng-schedtop --timerange "[15:12:34.037491350, 15:12:34.477824044]" /tmp/cyclictest-20160224/snapshot-1-20160224-201238-0
Checking the trace for lost events...
Processing the trace: 100% [####################################################################################################################################################] Time: 0:00:16 
Timerange: [2016-02-24 15:12:34.037491350, 2016-02-24 15:12:34.477824960]

Scheduling top
Wakeup               Switch                 Latency (us)   Priority  CPU   Wakee                      Waker                    
[15:12:19.174492582, 15:12:34.037505017]    14863012.435         20    3   lttng-consumerd (13358)    ktimersoftd/0 (4)        
[15:12:19.454490433, 15:12:34.037491350]    14583000.917         -2    3   ktimersoftd/3 (32)         ktimersoftd/0 (4)        
[15:12:20.049464909, 15:12:34.218199859]    14168734.950        -51    2   irq/22-Tegra PC (159)      stress (31182)           
[15:12:19.965607003, 15:12:34.064508073]    14098901.070         20    3   kworker/3:1 (1424)         kworker/1:2 (1402)       
[15:12:32.768959888, 15:12:34.037927682]     1268967.794       -100    3   cyclictest (27117)         ktimersoftd/2 (25)       
[15:12:34.064534489, 15:12:34.074489032]        9954.543         20    0   kworker/0:2 (1425)         kworker/1:2 (1402)       
[15:12:34.469802243, 15:12:34.477268463]        7466.220         -2    2   ktimersoftd/2 (25)         irq/154-hpd (161)        
[15:12:34.474464807, 15:12:34.477591545]        3126.738         20    2   rcuc/2 (24)                irq/154-hpd (161)        
[15:12:34.402909268, 15:12:34.403239100]         329.832         20    3   lttng-consumerd (13358)    ktimersoftd/3 (32)       
[15:12:34.477364879, 15:12:34.477608545]         243.666         20    2   rs:main Q:Reg (470)        in:imklog (469)

**Comment by abusque** [comment] 2016-04-26 20:37
This is fixed, but only the printed time range had an end beyond the value given in --timerange. No actual event was processed beyond the limit.

**Comment by abusque** [comment] 2016-04-27 19:36
Turns out the beginning of certain events is outside the specified timerange, so I'm reopening this until it is fixed.

**Comment by abusque** [comment] 2016-05-04 17:22
Alright so the verdict on this one is that it is not bug _per se_, but rather correct albeit not completely consistent behaviour. Events spanning multiple periods, or that began or ended outside of a given period should be shown in every period they cover. Currently however, only the period in which the spanning event has ended will display it, which is why these events, despite beginning before the starting bound of the period, are displayed.

The goal is thus to handle all event span cases, and if necessary add a flag to make it so periods only display events entirely contained within their bounds. I will close this issue, and probably open a new one shortly, describing a bit more rigorously the expected behaviour, and what is necessary to implement it.

**Closed by abusque** 2016-05-04 17:22 UTC
